version: "3"
services:
  web:
    image: frontier/nodewebsample:master
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    secrets:
      - TOPSECRET
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet: